# Generated by Django 6.0.3 on 2026-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('helper', 'Helper'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
